---
- name: copying files from grafana
  copy:
    src: ../files/
    dest: /tmp/grafana/
- name: creating grafana namespace
  community.kubernetes.k8s:
    name: grafana
    api_version: v1
    kind: Namespace
    state: present
- name: deploying grafana
  command: kubectl apply -f /tmp/grafana/deploy.yml
  register: deploygrafana
- debug: msg="{{ deploygrafana.stdout }}"
- name: config mal
  command: kubectl apply -f /tmp/grafana/config-map.yml
  register: configmap
- debug: msg="{{ configmap.stdout }}"
- name: svc
  command: kubectl apply -f /tmp/grafana/svc.yml
  register: deploygrafana
- debug: msg="{{ svc.stdout }}"