---
- name: adding kubernetes hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ item }}'
  loop:
    - "{{ nfs }} nfs nfs.acme.es"
    - "{{ master }} master master.acme.es"
    - "{{ worker0 }} worker0 worker0.acme.es"
    - "{{ worker1 }} worker1 worker1.acme.es"
- name: adding kernnel modules
  modprobe:
    name: br_netfilter
    state: present
- name: configuring firewalld
  firewalld:
    masquerade: yes
    permanent: true
    state: enabled
- name: enabling firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: True
- name: copying file k8s.conf
  copy:
    src: ../files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
- name: set authorized key taken from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
- name: disabling swap
  shell: |
    swapoff -a
- name: disabling swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'