---
- name: creating kubectl dir
  file:
    path: /root/.kube
    state: directory
- name: copying file kubectl
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
- name: modyfing file kubectl
  file:
    path: $HOME/.kube/config 
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
- name: checing nodes
  command: kubectl get nodes
  register: getnodes
- debug: msg="{{ getnodes.stdout }}"
