---
- name: setting kubeadm
  command: kubeadm config images pull
  register: configkubeadm
- debug: msg="{{ configkubeadm.stdout }}"
- name: setting firewalld
  command: firewall-cmd --zone=public --permanent --add-rich-rule 'rule family=ipv4 source address=172.17.0.0/16 accept'
- name: refreshing service firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: True
- name: setting pods network
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  ignore_errors: True
  register: configpodnet
- debug: msg="{{ configpodnet.stdout }}"