---
- name: installing kubernetes cluster
  hosts: all
  become: true
  vars:
    user: "terra"
    nfs: "nfs-jbrug91.westeurope.cloudapp.azure.com"
    master: "k8smaster-jbrug91.westeurope.cloudapp.azure.com"
    worker0: "k8sworker0-jbrug91.westeurope.cloudapp.azure.com"
    worker1: "k8sworker1-jbrug91.westeurope.cloudapp.azure.com"
  roles:
    - kubernetes
