---
- name: installing nfs service
  hosts: nfs
  become: true
  vars:
    master: "k8smaster-jbrug91.westeurope.cloudapp.azure.com"
    worker0: "k8sworker0-jbrug91.westeurope.cloudapp.azure.com"
    worker1: "k8sworker1-jbrug91.westeurope.cloudapp.azure.com"
  roles:
    - nfs
