---
- name: setting workers
  hosts: workers
  become: true
  vars:
    master: "10.0.1.10"
    token: "yw0ixs.rtjzw0ybfqb48adu"
    discoverytoken: "sha256:6ce53ecf51a90bed6bc1ecffd4263a391021de75e70574c01e153ff8b7801408"
  roles:
    - worker